version: '3'

services:
  wikidb:
    image: mongo:3
    expose:
      - '27017'
    command: '--smallfiles --bind_ip ::,0.0.0.0'
    environment:
      - 'MONGO_LOG_DIR=/dev/null'
    volumes:
      - wiki-mongodb:/data/db
  wikijs:
    image: 'requarks/wiki:latest'
    links:
      - wikidb
    depends_on:
      - wikidb
    ports:
      - '3001:3000'
    environment:
      WIKI_ADMIN_EMAIL: heschlie@gmail.com
    volumes:
      - /home/heschlie/projects/wikijs-docker/config.yml:/var/wiki/config.yml
      - 
